package asyncapi

import (
	"net/url"
	"strings"

	"github.com/MarkRosemaker/errpath"
)

// SecurityScheme defines a security scheme that can be used by the operations.
//
// Supported schemes are:
//   - User/Password.
//   - API key (either as user or as password).
//   - X.509 certificate.
//   - End-to-end encryption (either symmetric or asymmetric).
//   - HTTP authentication.
//   - HTTP API key.
//   - OAuth2's common flows (Implicit, Resource Owner Protected Credentials, Client Credentials and Authorization Code) as defined in [RFC6749].
//   - [OpenID Connect Discovery].
//   - SASL (Simple Authentication and Security Layer) as defined in [RFC4422].
//
// ([Specification])
//
// [RFC6749]: https://tools.ietf.org/html/rfc6749
// [OpenID Connect Discovery]: https://tools.ietf.org/html/draft-ietf-oauth-discovery-06
// [RFC4422]: https://tools.ietf.org/html/rfc4422
// [Specification]: https://www.asyncapi.com/docs/reference/specification/v3.1.0#securitySchemeObject
type SecurityScheme struct {
	// REQUIRED. The type of the security scheme.
	Type SecuritySchemeType `json:"type" yaml:"type"`
	// A short description for security scheme. CommonMark syntax MAY be used for rich text representation.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// REQUIRED for `httpApiKey`. The name of the header, query or cookie parameter to be used.
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	// REQUIRED for `apiKey` and `httpApiKey`. The location of the API key.
	// Valid values are `user` and `password` for `apiKey`
	// and `query`, `header` or `cookie` for `httpApiKey`.
	In SecuritySchemeIn `json:"in,omitempty" yaml:"in,omitempty"`
	// REQUIRED for `http`. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
	Scheme string `json:"scheme,omitempty" yaml:"scheme,omitempty"`
	// A hint to the client to identify how the bearer token is formatted, e.g. "jwt".
	// Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
	BearerFormat string `json:"bearerFormat,omitempty" yaml:"bearerFormat,omitempty"`
	// REQUIRED for `oauth2`. An object containing configuration information for the flow types supported.
	Flows *OAuthFlows `json:"flows,omitempty" yaml:"flows,omitempty"`
	// REQUIRED for `openIdConnect`. OpenId Connect URL to discover OAuth2 configuration values.
	// This MUST be in the form of an absolute URL.
	OpenIDConnectURL *url.URL `json:"openIdConnectUrl,omitempty" yaml:"openIdConnectUrl,omitempty"`
	// List of the needed scope names. An empty array means no scopes are needed.
	// Only valid for `oauth2` and `openIdConnect`.
	Scopes []string `json:"scopes,omitempty" yaml:"scopes,omitempty"`
	// This object MAY be extended with Specification Extensions.
	Extensions Extensions `json:",inline" yaml:",inline"`
}

const (
	// SecuritySchemeBearer is the value of SecurityScheme.Scheme for bearer tokens.
	SecuritySchemeBearer = "bearer"
	// SecuritySchemeBasic is the value of SecurityScheme.Scheme for basic authentication.
	SecuritySchemeBasic = "basic"
)

// Validate checks the security scheme for correctness.
func (s *SecurityScheme) Validate() error {
	if s.Type == "" {
		return &errpath.ErrField{Field: "type", Err: &errpath.ErrRequired{}}
	}

	if err := s.Type.Validate(); err != nil {
		return &errpath.ErrField{Field: "type", Err: err}
	}

	s.Description = strings.TrimSpace(s.Description)

	switch s.Type {
	case SecuritySchemeTypeAPIKey:
		if s.In == "" {
			return &errpath.ErrField{Field: "in", Err: &errpath.ErrRequired{}}
		}

		if err := s.In.validate(allSecuritySchemeInAPIKey); err != nil {
			return &errpath.ErrField{Field: "in", Err: err}
		}
	case SecuritySchemeTypeHTTPAPIKey:
		if s.Name == "" {
			return &errpath.ErrField{Field: "name", Err: &errpath.ErrRequired{}}
		}

		if s.In == "" {
			return &errpath.ErrField{Field: "in", Err: &errpath.ErrRequired{}}
		}

		if err := s.In.validate(allSecuritySchemeInHTTPAPIKey); err != nil {
			return &errpath.ErrField{Field: "in", Err: err}
		}
	case SecuritySchemeTypeHTTP:
		if s.Scheme == "" {
			return &errpath.ErrField{Field: "scheme", Err: &errpath.ErrRequired{}}
		}

		if SecuritySchemeBearer == strings.ToLower(s.Scheme) {
			s.Scheme = SecuritySchemeBearer // unify
		}
	case SecuritySchemeTypeOAuth2:
		if s.Flows == nil {
			return &errpath.ErrField{Field: "flows", Err: &errpath.ErrRequired{}}
		}

		if err := s.Flows.Validate(); err != nil {
			return &errpath.ErrField{Field: "flows", Err: err}
		}
	case SecuritySchemeTypeOpenIDConnect:
		if s.OpenIDConnectURL == nil {
			return &errpath.ErrField{Field: "openIdConnectUrl", Err: &errpath.ErrRequired{}}
		}

		if err := validateURL(s.OpenIDConnectURL); err != nil {
			return &errpath.ErrField{Field: "openIdConnectUrl", Err: err}
		}
	default: // no additional fields are required
	}

	// scopes are only valid for oauth2 and openIdConnect
	switch s.Type {
	case SecuritySchemeTypeOAuth2, SecuritySchemeTypeOpenIDConnect:
	default:
		if s.Scopes != nil {
			return &errpath.ErrField{Field: "scopes", Err: &errpath.ErrInvalid[string]{
				Message: `only valid for the types "oauth2" and "openIdConnect"`,
			}}
		}
	}

	return validateExtensions(s.Extensions)
}

func (l *loader) collectSecuritySchemeRefList(ss SecuritySchemeRefList, ref ref) {
	for i, s := range ss {
		l.collectSecuritySchemeRef(s, append(ref, itoa(i)))
	}
}

func (l *loader) collectSecuritySchemeRef(s *SecuritySchemeRef, ref ref) {
	collectRef(l, s, l.securitySchemes, ref)
}

func (l *loader) resolveSecuritySchemeRef(s *SecuritySchemeRef) error {
	return resolveRef(s, l.securitySchemes, nil)
}
