openapi: 3.1.0
info:
    title: Example API
    version: 1.0.0
    summary: This is an example API
    description: This is an *example* API
    termsOfService: https://www.example.com/terms
    contact:
        name: API Support
        url: https://www.example.com/support
        email: support@example.com
    license:
        name: Apache 2.0
        identifier: Apache-2.0
paths:
    /users/{id}: {}
components:
    schemas:
        SomeString:
            type: string
            pattern: ^[a-zA-Z0-9]+$